repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: fix-byte-order-marker
    -   id: end-of-file-fixer
ci:
    autoupdate_schedule: quarterly
